query SearchBox($query: String!, $max: Int!) {
  searchMixed(query: {query: $query}, first: $max) {
    aggregate {
      count
    }
    pageInfo {
      startCursor
      endCursor
    }
    edges {
      node {
        __typename
        ... on Book {
          id
          title
        }
        ... on Series {
          id
          title
        }
        ... on Author {
          id
          name
        }
      }
    }
  }
}
